# Generated by Django 5.0.2 on 2024-03-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothposts',
            name='user',
        ),
    ]
